### ISSUE TITLE
License - is this open source?

### ISSUE THREAD

**Issue by kiranandcode** [casperschipper/ocaml-cisp#1]
Hi! I happened to find this project from the link in your OCaml discuss profile, and it looks like something I would be interested in using. 

Before I try it out, I just wanted to check whether this project is open source as it doesn't currently list a license.

Could you add a license?

**Comment by casperschipper** [comment]
Hi there, of course, I have added a GPL-3 license.
The code is in a pretty "dynamic" state, but you are welcome to copy whatever appears useful or interesting for your purposes. Be sure to let me know if you have made something interesting (based on) it. 😀

**Comment by kiranandcode** [comment]
Perfect, thanks! Will have a try playing around with it!
